### ISSUE TITLE
FPC support

### ISSUE THREAD

**Issue by qindj** [VuioVuio/DelphiUCL#4]
Hi, 

Does this library support FPC? thanks~

**Comment by ghost** [comment]
Not yet, but I will consider it. I have no experience in FPC, so this could take a long time.

**Comment by srd-software** [comment]
FPC and Delphi are so similar yet so different at the same time. It takes a _lot_ of conditional defines to get the same code working for both. A good library to look at for examples of code and controls that work in FPC and Delphi is Alexey's ATFlatControls here on github.
